pipeline{
    agent any
   
    environment{
        AWS_REGION = "eu-north-1"
        S3_BUCKET = "taskmanager0123"
        CLOUDFRONT_DISTRIBUTION_ID = "E23JNKTP2I50R3"
    }
   
    options {
        timestamps()
    }
   
    stages{
       
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'frontend-credentials',
                    url: 'https://github.com/Kameshjustin/Mern-task-manager.git'
            }
        }
       
        stage('check node & NPM') {
            steps{
                sh '''
                  node -v
                  npm -v
                '''
            }
        }
       
        stage ('build') {
            steps {
                dir('frontend'){
                sh 'npm install'
                sh 'npm run build'
                }
            }
        }
        stage ('verify build output') {
            steps {
                 sh 'ls -la frontend/build'
            }
        }
        stage('deploy to s3'){
           
            steps {
                withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                    dir('frontend') {
                       
                        sh 'aws s3 sync build/ s3://${S3_BUCKET}/ --delete'
                   
                    }
                }
               
            }
        }
        stage('invalidate cloudfront'){
            when {
                expression { env.CLOUDFRONT_DISTRIBUTION_ID = "E23JNKTP2I50R3" }
            }
            steps {
                withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                    sh '''aws cloudfront create-invalidation \\
                        --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \\
                        --paths "/*"'''
                }
               
            }
           
        }
           
    }
    post {
        success {
            echo "✅ Deployment Successful! Your app is live."
        }
        failure {
            echo "❌ Pipeline failed. Check the logs for build or permission errors."
        }
    }
}


