pipeline {
    agent any
   
    environment {
        EC2_IP = "56.228.66.202"
        MONGO_URL = credentials('MONGODB_URI') 
    }
   
    stages {
        stage('checkout code') {
            steps {
                git branch: 'main',
                credentialsId: 'frontend-credentials',
                url: 'git@github.com:Kameshjustin/Mern-task-manager.git'
            }
        }
       
        stage('Deploy to EC2') {
            steps {
                sshagent(['task-manager1234ssh']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} << 'EOF'
                        set -e
                        mkdir -p /home/ubuntu/apps
                        cd /home/ubuntu/apps
                       
                        if [ ! -d "Mern-task-manager" ]; then
                           git clone git@github.com:Kameshjustin/Mern-task-manager.git
                        fi
                       
                        cd Mern-task-manager
                        git fetch origin
                        git checkout main
                        git pull origin main
                       
                        cd backend
                     
                        docker stop Backend-container || true
                        docker rm Backend-container || true
                        docker rmi mern-task-backend || true
 

                        docker build -t mern-task-backend .
                       

                        docker run -d \
                          --name Backend-container \
                          -p 5001:5001 \
                          -e MONGO_URI="${MONGO_URL}" \
                          mern-task-backend
EOF
                    """
                }
            }
        }
    }
   
    post {
        success { echo "🚀 DEPLOYMENT SUCCESSFUL" }
        failure { echo "❌ DEPLOYMENT FAILED - Check Jenkins Console Output" }
    }
}
